#!/bin/bash
# Reinitialize the server keys each time we boot up; that way the docker image
# doesn't contain any sensitive data.

cd /etc/openvpn
ln -s easy-rsa-source/easy-rsa/2.0 easy-rsa

cd /etc/openvpn/easy-rsa
source ./vars
./clean-all
./build-dh
./pkitool --initca
./pkitool --server server

mkdir -p keys

mv /home/vpn/openvpn-client.conf easy-rsa/keys/client.conf

for ip_last in `seq 4 4 255`; do
  ip=IP_BASE_PREFIX.$ip_last
  hostname=ip_${ip//./_}
  peer_ip=${ip%.*}.$((${ip##*.} - 1))
  group_ip=${ip%.*}.0             # NB: change this if you change subnet
  subnet=255.255.255.0
  echo "generating key for $ip..."

  cd /etc/openvpn/easy-rsa

  # Create the client key unless we have one already
  source ./vars
  export KEY_CN=$hostname
  export KEY_ORG=zerovpn
  export KEY_EMAIL=none
  ./pkitool $hostname > /dev/null

  cat > ../clients/$hostname <<EOF
ifconfig-push $ip $peer_ip
route $group_ip $subnet
EOF

  cd /etc/openvpn/easy-rsa/keys
  tar -c ca.crt $hostname.crt $hostname.key client.conf > /home/vpn/$hostname
done

cd /
/etc/init.d/openvpn start
/usr/sbin/sshd -D
