#!/bin/bash
# This is used from inside the vpn container.
#
# Usage:
# $ sudo new-client client_ip

ip=$1
hostname=ip_${ip//./_}

cd /etc/openvpn/easy-rsa/keys
tar -c ca.crt $hostname.crt $hostname.key client.conf
